// The one list of UI features. Adding a feature is a folder under ./features and a line here.
export default [
  "./features/modes/index.js",
  "./features/log/index.js",
  "./features/projects/index.js",
  "./features/media/index.js",
  "./features/placeholders/early.js",
  "./features/dock/index.js",
  "./features/keys/index.js",
  "./features/timeline/index.js",
  "./features/inspector/index.js",
  "./features/generate/index.js",
  "./features/preview/index.js",
  "./features/menus/index.js",
  "./features/render/index.js",
  "./features/render/selected.js",
  "./features/rating/index.js",
  "./features/status/index.js",
  "./features/audio/index.js",
  "./features/montage/index.js",
  "./features/generate/warn.js",
  "./features/composer/index.js",
  "./features/settings/index.js",
  "./features/welcome/index.js",
  "./features/temp/index.js",
].map((path) => new URL(path, import.meta.url).href);
